### ISSUE TITLE
Missing `dist` in the published package on npm

### ISSUE THREAD

**Issue by psmyrek** [r3dDoX/vite-plugin-svgo#3]
Hi, I noticed that v1.5.0 does not contain `dist` on npm:

![obraz](https://github.com/user-attachments/assets/003ebbee-08e3-443b-8787-15778d794971)

Could you please fix it?

**Comment by cmahnke** [comment]
Gives:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'site/node_modules/vite-plugin-svgo/dist/index.js' imported from site/node_modules/vite-plugin-svgo/exports/import.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:255:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)

```

**Comment by qeleb** [comment]
+1

**Comment by EzeFSpa** [comment]
Same error here

![image](https://github.com/user-attachments/assets/c77a31fe-fdd5-4932-99c9-b0e5e4a01f6c)

**Comment by TullariS** [comment]
+1

**Comment by r3dDoX** [comment]
Sorry for the delay, I'm looking into that. Apparently my github action failed silently and still published the version even though the build failed.

**Comment by r3dDoX** [comment]
Alright, this was a bit of tricky typescript issue because of a version upgrade. I fixed it and released it with version 1.6.2. :+1:

**Comment by eliandoran** [comment]
Hi, @r3dDoX .

Seems this issue came back with the release of 3.0.0?
